apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: nginx
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.100.231-192.168.100.250
